var text;
text = '';
text += '#Robo Markdown\n'
text += '\n'
text += 'you can write and edit any \n'
text += '[Markdown](http://daringfireball.net/projects/markdown/syntax) \n'
text += 'syntax in here and watch it render live\n'
text += '\n'
text += '####Cool features to add\n'
text += '\n'
text += '- Save and load files \n'
text += '- resize editor / renderer windows\n'
text += '- come up with a better name\n'
text += '\n'
text += '####Did I mention it has syntax highlighting?\n'
text += '\n'
text += '```\n'
text += 'alias yolo=\'git commit -am "DEAL WITH IT" && git push -f origin master\'\n'
text += '```\n'
text += '\n'
text += '####To get started\n'
text += '\n'
text += '1. Clone repo.\n'
text += '2. ```cd``` to the project\n'
text += '3. ```npm install```\n'
text += '4. ```npm start```\n'
text += '5. Go to ```localhost:3000```\n'
text += '\n'
text += '####Thats about it\n'
text += '\n'
text += '![mic drop](http://i.giphy.com/149R89yoMrIFgI.gif)\n'

module.exports = text;
